#ifndef EVENTS_HPP
#define EVENTS_HPP

#include "types.hpp"
#include <string>
#include <sstream>

// ============================================================================
// EVENT SYSTEM - Event Sourcing Architecture
// ============================================================================

enum class EventType {
    NEW_ORDER,
    CANCEL_ORDER,
    TRADE,
    SNAPSHOT
};

// Base event class
struct Event {
    EventType type;
    Timestamp timestamp;
    
    virtual ~Event() = default;
    virtual std::string to_string() const = 0;
    
protected:
    Event(EventType t, Timestamp ts) : type(t), timestamp(ts) {}
};

// ============================================================================
// NEW ORDER EVENT
// ============================================================================

struct NewOrderEvent : Event {
    OrderId order_id;
    Side side;
    Price price;
    Quantity quantity;
    
    NewOrderEvent(Timestamp ts, OrderId id, Side s, Price p, Quantity q)
        : Event(EventType::NEW_ORDER, ts), 
          order_id(id), side(s), price(p), quantity(q) {}
    
    std::string to_string() const override {
        std::stringstream ss;
        ss << "NEW_ORDER," << timestamp.get() << "," 
           << order_id.get() << "," << ::to_string(side) << "," 
           << price.get() << "," << quantity.get();
        return ss.str();
    }
};

// ============================================================================
// CANCEL ORDER EVENT
// ============================================================================

struct CancelOrderEvent : Event {
    OrderId order_id;
    
    CancelOrderEvent(Timestamp ts, OrderId id)
        : Event(EventType::CANCEL_ORDER, ts), order_id(id) {}
    
    std::string to_string() const override {
        std::stringstream ss;
        ss << "CANCEL_ORDER," << timestamp.get() << "," 
           << order_id.get();
        return ss.str();
    }
};

// ============================================================================
// TRADE EVENT (Generated by system)
// ============================================================================

struct TradeEvent : Event {
    OrderId passive_order_id;
    OrderId aggressive_order_id;
    Price price;
    Quantity quantity;
    
    TradeEvent(Timestamp ts, OrderId passive, OrderId aggressive, 
               Price p, Quantity q)
        : Event(EventType::TRADE, ts), 
          passive_order_id(passive), 
          aggressive_order_id(aggressive), 
          price(p), quantity(q) {}
    
    std::string to_string() const override {
        std::stringstream ss;
        ss << "TRADE," << timestamp.get() << "," 
           << passive_order_id.get() << "," 
           << aggressive_order_id.get() << "," 
           << price.get() << "," << quantity.get();
        return ss.str();
    }
};

#endif